apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.shipments.name }}
  labels:
    app: {{ .Values.shipments.name }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.shipments.name }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.shipments.port }}
      name: http